  await page.locator('body').click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').fill('m');
  await page.getByText('Maths', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Maths$/ }).nth(1).click();
  await page.locator('#subjectsInput').fill('e');
  await page.getByText('Chemistry', { exact: true }).click();
  await page.locator('#subjectsInput').fill('');
});

  await page.getByRole('option', { name: 'Choose Wednesday, February 10th,' }).click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').fill('1');
  await page.locator('div').filter({ hasText: /^Sports$/ }).click();
  await page.locator('div').filter({ hasText: /^Reading$/ }).click();
  await page.getByText('Music').click();
  await page.getByRole('button', { name: 'Select picture' }).click();
  await page.getByRole('button', { name: 'Select picture' }).setInputFiles('next');
  await page.getByRole('textbox', { name: 'Current Address' }).click();
  await page.getByRole('textbox', { name: 'Current Address' }).fill('11');
  await page.getByText('Select State').click();
  await page.getByText('Uttar Pradesh', { exact: true }).click();
  await page.getByText('Select City').click();
  await page.getByText('Agra', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demoqa.com/automation-practice-form');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('1`');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('1');
  await page.getByRole('textbox', { name: 'Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'name@example.com' }).fill('dkfn@gmail.com');
  await page.getByRole('textbox', { name: 'name@example.com' }).press('Tab');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('Tab');
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('1111111111');
  await page.locator('#dateOfBirthInput').click();
  await page.getByRole('option', { name: 'Choose Tuesday, December 9th,' }).click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').fill('m');
  await page.getByText('Maths', { exact: true }).click();
  await page.getByText('Sports').click();
  await page.getByRole('button', { name: 'Select picture' }).click();
  await page.getByRole('button', { name: 'Select picture' }).setInputFiles('package.json');
  await page.getByRole('textbox', { name: 'Current Address' }).click();
  await page.getByRole('textbox', { name: 'Current Address' }).fill('w');
  await page.getByText('Select State').click();
  await page.getByText('NCR', { exact: true }).click();
  await page.getByText('Select City').click();
  await page.getByText('Delhi', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Thanks for submitting the form').click();
  await page.getByText('Thanks for submitting the form').click();
  await page.getByText('Thanks for submitting the form').click();
  await page.getByText('Thanks for submitting the form').click();
  await page.getByText('Thanks for submitting the form').click();
  await page.getByText('Thanks for submitting the form').click();
  await page.locator('div').filter({ hasText: 'Thanks for submitting the form' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Thanks for submitting the form' }).nth(3).click();
  await page.getByText('Thanks for submitting the form').click();
  await page.locator('div').filter({ hasText: 'Thanks for submitting the form' }).nth(3).click();
});
});